#!/bin/sh

export RESTFRAMESSYS=$PWD
export DYLD_LIBRARY_PATH=$RESTFRAMESSYS/lib:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$RESTFRAMESSYS/lib:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$RESTFRAMESSYS/include:${CPLUS_INCLUDE_PATH:-""}
