ROOTCONF                = @ROOTCONF@
ROOTCINT                = @ROOTCINT@
ROOTLDFLAGS             = -L@ROOTLIBDIR@ @ROOTLIBS@ @ROOTAUXLIBS@
ROOTCXXFLAGS            = @ROOTCFLAGS@ 
ROOTAUXCXXFLAGS         = @ROOTAUXCFLAGS@
